spring:
  application:
    name: telegram bot QR code
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5436/tgQRBot
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

telegram:
  bot:
    username: QrCodeGenMasterBot
    token: 7410420840:AAEZwcz3m62F71S8HVJpgGj0s9EbO1y-61A

geoip:
  database:
    path: src/main/resources/GeoLite2-City_20240730/GeoLite2-City.mmdb
