spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO}
    database: ${SPRING_JPA_DATABASE}
    database-platform: ${SPRING_JPA_DATABASE-PLATFORM}
  flyway:
    baseline-on-migrate: ${SPRING_FLYWAY_BASELINE-ON-MIGRATE}
    locations: ${SPRING_FLYWAY_LOCATIONS}
    enabled: ${SPRING_FLYWAY_ENABLED}
    baseline-description: ${SPRING_FLYWAY_BASELINE-DESCRIPTION}
    baseline-version: ${SPRING_FLYWAY_BASELINE-VERSION}
    user: ${SPRING_FLYWAY_USER}
    password: ${SPRING_FLYWAY_PASSWORD}

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}

geoip:
  database:
    path: ${GEOIP_DATABASE_PATH}



